/*CREATE USER C##KH5 IDENTIFIED BY 1234;
GRANT CONNECT , RESOURCE TO C##KH5;
ALTER USER C##KH5 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;*/

-- DROP
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE MEMO CASCADE CONSTRAINTS;
DROP TABLE MESSAGE CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE HEADER CASCADE CONSTRAINTS;
DROP TABLE MEM_HEADER CASCADE CONSTRAINTS;
DROP TABLE DRAMA_BOARD CASCADE CONSTRAINTS;
DROP TABLE NOTICE_BOARD CASCADE CONSTRAINTS;
DROP TABLE DRAMA_BOARD_REPLY CASCADE CONSTRAINTS;
DROP TABLE NOTICE_BOARD_REPLY CASCADE CONSTRAINTS;
DROP TABLE DRAMA_BOARD_FILE CASCADE CONSTRAINTS;
DROP TABLE DRAMA_BOARD_SCRAP CASCADE CONSTRAINTS;
DROP TABLE DRAMA_BOARD_BLAME CASCADE CONSTRAINTS;



DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_ADMIN_NO;
DROP SEQUENCE SEQ_MEMO_NO;
DROP SEQUENCE SEQ_MESSAGE_NO;
DROP SEQUENCE SEQ_HEADER_NO;
DROP SEQUENCE SEQ_MEM_HEADER_NO;
DROP SEQUENCE SEQ_DRAMA_BOARD_NO;
DROP SEQUENCE SEQ_NOTICE_BOARD_NO;
DROP SEQUENCE SEQ_DRAMA_BOARD_REPLY_NO;
DROP SEQUENCE SEQ_NOTICE_BOARD_REPLY_NO;
DROP SEQUENCE SEQ_DRAMA_BOARD_FILE_NO;
DROP SEQUENCE SEQ_DRAMA_BOARD_SCRAP_NO;
DROP SEQUENCE SEQ_DRAMA_BOARD_BLAME_NO;
DROP SEQUENCE SEQ_CATEGORY_NO;

CREATE TABLE MEMBER (
	MEM_NUM	NUMBER		NOT NULL,
	MEM_ID	VARCHAR2(100)		NULL,
	MEM_PWD	VARCHAR2(100)		NULL,
	MEM_NICK	VARCHAR2(100)		NULL,
	MEM_BIRTH	CHAR(6)		NULL,
	MEM_PHON	CHAR(11)		NULL,
	MEM_POINT	NUMBER		NULL,
	MEM_STATUS	CHAR(1)		DEFAULT 'O' CHECK (MEM_STATUS IN ('O','X'))
);
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;


CREATE TABLE ADMIN (
	ADMIN_NUM	NUMBER		NOT NULL,
	MEM_NUM	NUMBER		NOT NULL,
	ADMIN_PWD	VARCHAR2(100)		NULL,
	ADMIN_LEVEL	NUMBER		NULL
);
CREATE SEQUENCE SEQ_ADMIN_NO NOCACHE NOCYCLE;


CREATE TABLE MEMO (
	MEMO_NUM	NUMBER		NOT NULL,
	MEMO_WRITER	NUMBER		NOT NULL,
    MEMO_TARGET	VARCHAR(100)		NOT NULL,
	MEMO_CONTENT	VARCHAR(100)		NULL,
    MEMO_ENROLL_DATE	TIMESTAMP		 DEFAULT SYSDATE
);
CREATE SEQUENCE SEQ_MEMO_NO NOCACHE NOCYCLE;


CREATE TABLE MESSAGE (
	MSG_NUM	NUMBER		NOT NULL,
	MSG__SENDER	VARCHAR2(100)		NOT NULL,
	MSG_RECEIVER	VARCHAR2(100)		NOT NULL,
	MSG__CONTENT	VARCHAR2(1000)		NULL,
	MSG__ENROLL_DATE	TIMESTAMP		 DEFAULT SYSDATE,
	MSG__TITLE	VARCHAR2(100)		NULL,
	MSG_STATUS	CHAR(1)		DEFAULT 'O' CHECK (MSG_STATUS IN ('O','X')),
	MSG_READ_DATETIME	TIMESTAMP		 
);
CREATE SEQUENCE SEQ_MESSAGE_NO NOCACHE NOCYCLE;


CREATE TABLE CATEGORY (
	CAT_NUM	NUMBER		NOT NULL,
	CAT_NAME	VARCHAR(100)		NULL
);
CREATE SEQUENCE SEQ_CATEGORY_NO NOCACHE NOCYCLE;


CREATE TABLE HEADER (
	HEADER_NUM	NUMBER		NOT NULL,
	HEADER_NAME	VARCHAR2(100)		NULL
);
CREATE SEQUENCE SEQ_HEADER_NO NOCACHE NOCYCLE;


CREATE TABLE MEM_HEADER (
	MEM_HEAD_NUM	NUMBER		NOT NULL,
	MEM_NUM	NUMBER		NOT NULL,
	HEADER_NUM	NUMBER		NOT NULL
);
CREATE SEQUENCE SEQ_MEM_HEADER_NO NOCACHE NOCYCLE;


CREATE TABLE DRAMA_BOARD (
	DRAMA_BRD_NUM	NUMBER		NOT NULL,
	DRAMA_WRITER	NUMBER		NOT NULL,
	CAT_NUM	NUMBER		NOT NULL,
    HEADER_NUM NUMBER ,
	TITLE	VARCHAR2(100)		NULL,
	CONTENT	VARCHAR2(4000)		NULL,
	STATUS	CHAR(1)		DEFAULT 'O' CHECK (STATUS IN ('O','X')),
	ENROLL_DATE	TIMESTAMP		 DEFAULT SYSDATE,
	MODIFY_DATE	TIMESTAMP		NULL,
	HIT	NUMBER		DEFAULT 0,
	ANONYMITY	CHAR(1)		DEFAULT 'X' CHECK (ANONYMITY IN ('O','X'))
);
CREATE SEQUENCE SEQ_DRAMA_BOARD_NO NOCACHE NOCYCLE;


CREATE TABLE NOTICE_BOARD (
	NOTICE_NUM	NUMBER		NOT NULL,
	ADMIN_NUM	NUMBER		NOT NULL,
	TITLE	VARCHAR2(100)		NULL,
	CONTENT	VARCHAR2(4000)		NULL,
	STATUS	CHAR(1)		DEFAULT 'O' CHECK (STATUS IN ('O','X')),
	ENROLL_DATE	TIMESTAMP		DEFAULT SYSDATE,
	MODIFY_DATE	TIMESTAMP		NULL,
	HIT	NUMBER		DEFAULT 0
);
CREATE SEQUENCE SEQ_NOTICE_BOARD_NO NOCACHE NOCYCLE;


CREATE TABLE DRAMA_BOARD_REPLY (
	RE_NO	NUMBER		NOT NULL,
	RE_WRITER	NUMBER		NOT NULL,
	DRAMA_BRD_NUM	NUMBER		NOT NULL,
	RE_REF	NUMBER		 NOT NULL,
	RE_CONTENT	VARCHAR2(1000)	NOT	NULL,
	RE_ANONYMITY	CHAR(1)		DEFAULT 'X' CHECK (RE_ANONYMITY IN ('O','X')),
	RE_ENROLL_DATE	TIMESTAMP		DEFAULT SYSDATE,
	RE_STATUS	CHAR(1)		DEFAULT 'O' CHECK (RE_STATUS IN ('O','X'))
);
CREATE SEQUENCE SEQ_DRAMA_BOARD_REPLY_NO NOCACHE NOCYCLE;


CREATE TABLE NOTICE_BOARD_REPLY (
	NOTICE_RE_NO	NUMBER		NOT NULL,
	NOTICE_NUM	NUMBER		NOT NULL,
	RE_CONTENT	VARCHAR2(1000)		NULL,
	RE_ENROLL_DATE	TIMESTAMP		DEFAULT SYSDATE,
	RE_STATUS	CHAR(1)		DEFAULT 'O' CHECK (RE_STATUS IN ('O','X')),
	RE_REF	NUMBER		NULL,
	RE_ANONYMITY	CHAR(1)		DEFAULT 'X' CHECK (RE_ANONYMITY IN ('O','X'))
);
CREATE SEQUENCE SEQ_NOTICE_BOARD_REPLY_NO NOCACHE NOCYCLE;


CREATE TABLE DRAMA_BOARD_FILE (
	FILE_NO	NUMBER		NOT NULL,
	DRAMA_BRD_NUM	NUMBER		NOT NULL,
	ORIGIN_NAME	VARCHAR2(1000)		NULL,
	CHANGE_NAME	VARCHAR2(1000)		NULL,
	ENROLL_DATE	TIMESTAMP		DEFAULT SYSDATE,
	STATUS	CHAR(1)		DEFAULT 'O' CHECK (STATUS IN ('O','X'))
);
CREATE SEQUENCE SEQ_DRAMA_BOARD_FILE_NO NOCACHE NOCYCLE;


CREATE TABLE DRAMA_BOARD_SCRAP (
	SCRAP_NO	NUMBER		NOT NULL,
	DRAMA_BRD_NUM	NUMBER		NOT NULL,
	MEM_NUM	NUMBER		NOT NULL
);
CREATE SEQUENCE SEQ_DRAMA_BOARD_SCRAP_NO NOCACHE NOCYCLE;


CREATE TABLE DRAMA_BOARD_BLAME (
	DRAMA_BLAME_NUM	NUMBER		NOT NULL,
	BLAME_WRITER	NUMBER		NOT NULL,
	DRAMA_BRD_NUM	NUMBER		NOT NULL,
	CONTENT	VARCHAR2(1000)		NULL,
	ENROLL_DATE	TIMESTAMP		DEFAULT SYSDATE,
	STATUS	CHAR(1)		DEFAULT 'X' CHECK (STATUS IN ('O','X'))
);
CREATE SEQUENCE SEQ_DRAMA_BOARD_BLAME_NO NOCACHE NOCYCLE;



--샘플 데이터 (MEMBER)
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'ADMIN', '1234', '관리자');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user01', '1234', '고남순');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user02', '1234', '이수하');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user03', '1234', '최택');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user04', '1234', '도롱뇽');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user05', '1234', '담덕');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user06', '1234', '수지니');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user07', '1234', '서영이');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user08', '1234', '우영우');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user09', '1234', '권모술수');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user10', '1234', '최수연');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user11', '1234', '짱변');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user12', '1234', '윤윤제');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user13', '1234', '성시원');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user14', '1234', '덕선이');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user15', '1234', '도롱뇽');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user16', '1234', '기하');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user17', '1234', '탄야');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user18', '1234', '은섬');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user19', '1234', '태알하');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user20', '1234', '도학찬');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user21', '1234', '정인재');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user22', '1234', '강세찬');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user23', '1234', '송하경');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user24', '1234', '주무치');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user25', '1234', '처로');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user26', '1234', '고혜미');
INSERT INTO MEMBER(MEM_NUM, MEM_ID, MEM_PWD, MEM_NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'user27', '1234', '송삼동');
COMMIT;

--샘플 데이터(CATEGORY)
INSERT INTO CATEGORY(CAT_NUM,CAT_NAME) VALUES(SEQ_CATEGORY_NO.NEXTVAL,'잡담');
INSERT INTO CATEGORY(CAT_NUM,CAT_NAME) VALUES(SEQ_CATEGORY_NO.NEXTVAL ,'리뷰');
INSERT INTO CATEGORY(CAT_NUM,CAT_NAME) VALUES(SEQ_CATEGORY_NO.NEXTVAL ,'정보');
COMMIT;


--샘플 데이터(DRAMA_BOARD)
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 1 ,'태왕사신기 재밌나요' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 1 ,'태왕사신기 재밌나요2' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,3 , 1 ,'태왕사신기 재밌나요3' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 1 ,'태왕사신기 재밌나요4' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,4 , 1 ,'태왕사신기 재밌나요5' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 1 ,'태왕사신기 재밌나요' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 1 ,'태왕사신기 재밌나요2' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,3 , 1 ,'태왕사신기 재밌나요3' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 2 ,'태왕사신기 재밌나요4' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,4 , 3 ,'태왕사신기 재밌나요5' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 2 ,'태왕사신기 재밌나요' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 3 ,'태왕사신기 재밌나요2' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,3 , 1 ,'태왕사신기 재밌나요3' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 2 ,'태왕사신기 재밌나요4' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 2 ,'태왕사신기 재밌나요4' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 2 ,'태왕사신기 재밌나요4' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 2 ,'태왕사신기 재밌나요4' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,HEADER_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 2 ,1,'태왕사신기 재밌나요4' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,HEADER_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 2 ,2,'태왕사신기 재밌나요4' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,HEADER_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 2 ,3,'태왕사신기 재밌나요4' ,'오래된 드라마인테 추천하시는지?' );
INSERT INTO DRAMA_BOARD(DRAMA_BRD_NUM,DRAMA_WRITER,CAT_NUM,HEADER_NUM,TITLE,CONTENT) VALUES(SEQ_DRAMA_BOARD_NO.NEXTVAL ,2 , 2 ,3,'태왕사신기 재밌나요4' ,'오래된 드라마인테 추천하시는지?' );
COMMIT;

--샘플데이터(memo)
INSERT INTO MEMO (MEMO_NUM, MEMO_WRITER, MEMO_TARGET,MEMO_CONTENT) VALUES (SEQ_MEMO_NO.NEXTVAL, 1, 2,'힘내자');
INSERT INTO MEMO (MEMO_NUM, MEMO_WRITER, MEMO_TARGET,MEMO_CONTENT) VALUES (SEQ_MEMO_NO.NEXTVAL, 2, 3,'파이팅');
INSERT INTO MEMO (MEMO_NUM, MEMO_WRITER, MEMO_TARGET,MEMO_CONTENT) VALUES (SEQ_MEMO_NO.NEXTVAL, 3, 2,'메모끝내자');
INSERT INTO MEMO (MEMO_NUM, MEMO_WRITER, MEMO_TARGET,MEMO_CONTENT) VALUES (SEQ_MEMO_NO.NEXTVAL, 1, 3,'파이팅');
INSERT INTO MEMO (MEMO_NUM, MEMO_WRITER, MEMO_TARGET,MEMO_CONTENT) VALUES (SEQ_MEMO_NO.NEXTVAL, 3, 1,'메모끝내자');
commit;

--샘플데이터(DRAMA_BOARD_REPLY)
INSERT INTO DRAMA_BOARD_REPLY(RE_NO,RE_WRITER,DRAMA_BRD_NUM,RE_REF,RE_CONTENT) VALUES(SEQ_DRAMA_BOARD_REPLY_NO.NEXTVAL, 2 , 17 , 2 , '댓글2') ;
INSERT INTO DRAMA_BOARD_REPLY(RE_NO,RE_WRITER,DRAMA_BRD_NUM,RE_REF,RE_CONTENT) VALUES(SEQ_DRAMA_BOARD_REPLY_NO.NEXTVAL, 2 , 17 , 2 , '댓글3') ;
INSERT INTO DRAMA_BOARD_REPLY(RE_NO,RE_WRITER,DRAMA_BRD_NUM,RE_REF,RE_CONTENT) VALUES(SEQ_DRAMA_BOARD_REPLY_NO.NEXTVAL, 2 , 17 , 2 , '댓글4') ;
INSERT INTO DRAMA_BOARD_REPLY(RE_NO,RE_WRITER,DRAMA_BRD_NUM,RE_REF,RE_CONTENT) VALUES(SEQ_DRAMA_BOARD_REPLY_NO.NEXTVAL, 2 , 17 , 2 , '댓글5') ;
INSERT INTO DRAMA_BOARD_REPLY(RE_NO,RE_WRITER,DRAMA_BRD_NUM,RE_REF,RE_CONTENT) VALUES(SEQ_DRAMA_BOARD_REPLY_NO.NEXTVAL, 3 , 17 , 4 , '댓글6') ;
INSERT INTO DRAMA_BOARD_REPLY(RE_NO,RE_WRITER,DRAMA_BRD_NUM,RE_REF,RE_CONTENT) VALUES(SEQ_DRAMA_BOARD_REPLY_NO.NEXTVAL, 2 , 17 , 2 , '댓글7') ;
INSERT INTO DRAMA_BOARD_REPLY(RE_NO,RE_WRITER,DRAMA_BRD_NUM,RE_REF,RE_CONTENT) VALUES(SEQ_DRAMA_BOARD_REPLY_NO.NEXTVAL, 3 , 17 , 3 , '댓글7') ;
COMMIT;
